openapi: "3.1.0"
info:
  title: "minestomcn_backend API"
  description: "minestomcn_backend API"
  version: "1.0.0"
servers:
- url: "https://minestomcn_backend"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /api/libraries:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"